apiVersion: v1
kind: Service
metadata:
  name: demo-crm-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: demo-crm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000