apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-ctrl
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: ./charts/nginx-ingress-controller
    repoURL: http://54.219.29.131:8084/gitlab-instance-34f73614/portfolio_gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true