apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: startup
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: app_of_apps/apps
    repoURL: http://54.219.29.131:8084/gitlab-instance-34f73614/portfolio_gitops.git
    targetRevision: HEAD
  project: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false